sudo: required
services:
  - docker

before_install:
  - docker build -t megagrindstone/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true megagrindstone/react-test npm test

after_success:
  - docker build -t megagrindstone/multi-client ./client
  - docker build -t megagrindstone/multi-nginx ./nginx
  - docker build -t megagrindstone/multi-server ./server
  - docker build -t megagrindstone/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push megagrindstone/multi-client
  - docker push megagrindstone/multi-nginx
  - docker push megagrindstone/multi-server
  - docker push megagrindstone/multi-worker